### ISSUE TITLE
Make ServiceTracker app postgres compatible

### ISSUE THREAD

**Issue by hasheddan** [kubevela/samples#27]
In order for the `ServiceTracker` app to be made portable across different infrastructure currently supported by Crossplane, it needs to be updated to use Postgres as its database instead of MongoDB (or to be able to be deployed with either).

**Comment by artursouza** [comment]
Please, assign this to me.

**Comment by artursouza** [comment]
Please, review https://github.com/oam-dev/samples/pull/28
